# Generated by Django 6.0.4 on 2026-04-28 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_warnings_per_day', models.IntegerField(default=3)),
                ('max_violations_before_expel', models.IntegerField(default=3)),
                ('audio_threshold', models.IntegerField(default=500, help_text='RMS audio level threshold for talking detection')),
                ('cooldown_seconds', models.IntegerField(default=30, help_text='Minimum seconds between warnings for the same person')),
                ('auto_reset_daily', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule_config', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('warning_count', models.IntegerField(default=0)),
                ('is_expelled', models.BooleanField(default=False, help_text='Student asked to leave for the day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'date'], name='violations__organiz_a86796_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(1, 'Warning 1 — Notification'), (2, 'Warning 2 — Strong Alert'), (3, 'Warning 3 — Violation Marked')])),
                ('reason', models.CharField(default='Talking detected', max_length=300)),
                ('camera_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='violations__user_id_d3588a_idx')],
            },
        ),
    ]
