# Generated by Django 4.2.30 on 2026-08-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attentionsnapshot',
            new_name='attention_a_session_92a26b_idx',
            old_name='attention_snapshot_session_ts_idx',
        ),
        migrations.AlterField(
            model_name='attentionsession',
            name='aggregate_only',
            field=models.BooleanField(default=True, help_text='When True (default), only class-wide attention % is displayed. No per-slot (anonymous) cards are shown. Recommended for all deployments.'),
        ),
    ]
